RANDOM_SEED: 0

PHASE: "training"
EXPERIMENT_NAME: "ai_aesthetics_optim"
RESULTS_DIR: "/storage/acadia2020_graphcnn_training_results"
OVERFIT: True

SHAPENET_DATA:
    PATH: "/storage/acadia2020_graphcnn_dataset"

OPTIM:
    BATCH_SIZE: 4
    VAL_BATCH_SIZE: 4
    WORKERS: 8
    EPOCH: 250
    LR: 0.0002
    MOMENTUM: 0.9
    WEIGHT_DECAY: 0.005
    CLIP_GRADIENTS: 12.5

GCC:
    INPUT_MESH_FEATS: 3
    HIDDEN_DIMS: [128, 256, 256, 512]
    CLASSES: 10
    CONV_INIT: "normal"
